"""empty message

Revision ID: bd5ba0e69c01
Revises: 2bb8e0bbd1f4
Create Date: 2018-05-14 18:36:41.140628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd5ba0e69c01'
down_revision = '2bb8e0bbd1f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nome', sa.String(length=80), nullable=False))
    op.add_column('users', sa.Column('sobrenome', sa.String(length=80), nullable=False))
    op.drop_column('users', 'segundoNome')
    op.drop_column('users', 'primeiroNome')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('primeiroNome', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('segundoNome', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_column('users', 'sobrenome')
    op.drop_column('users', 'nome')
    # ### end Alembic commands ###
